### ISSUE TITLE
Error after update to 2.2.2. and 2.2.3

### ISSUE THREAD

**Issue by gutesshop** [Magenerds/BasePrice#28]
Hi,

i got an error after updating the Magento Shop to version 2.2.2 and 2.2.3.

If i open the config, i got this error:

Exception #0 (InvalidArgumentException): Unable to unserialize value.

Exception #0 (InvalidArgumentException): Unable to unserialize value.
#0 /usr/local/vhosts/test-design/www/vendor/magento/module-config/Model/Config/Backend/Serialized.php(55): Magento\Framework\Serialize\Serializer\Json->unserialize('a:23:{i:0;a:3:{...')
#1 /usr/local/vhosts/test-design/www/vendor/magento/framework/Model/AbstractModel.php(601): Magento\Config\Model\Config\Backend\Serialized->_afterLoad()
#2 /usr/local/vhosts/test-design/www/vendor/magento/module-config/Block/System/Config/Form.php(441): Magento\Framework\Model\AbstractModel->afterLoad()
#3 /usr/local/vhosts/test-design/www/vendor/magento/module-config/Block/System/Config/Form.php(349): Magento\Config\Block\System\Config\Form->getFieldData(Object(Magento\Config\Model\Config\Structure\Element\Field\Interceptor), 'baseprice/gener...')
#4 /usr/local/vhosts/test-design/www/vendor/magento/module-config/Block/System/Config/Form.php(325): Magento\Config\Block\System\Config\Form->_initElement(Object(Magento\Config\Model\Config\Structure\Element\Field\Interceptor), Object(Magento\Framework\Data\Form\Element\Fieldset), 'baseprice/gener...', '', '')

**Comment by sydekumf** [comment]
Hey, seems like the serialization issue when Magento changed the serializer logic. Can you delete the database entries in `core_config` for every Base Price entry for the the unit mapping and resave them in the system configuration in the backend?
Please be sure to do proper back ups before you do this. Thanks!

**Comment by gewaechshaus** [comment]
@sydekumf - had the same issue on a 2.2.4 system and the fix you provided did work, just to let you know. Viele Grüße Jan
